### ISSUE TITLE
Stuck at "Waiting for root device /dev/mmcblk0p2"

### ISSUE THREAD

**Issue by ghost** [fail0verflow/switch-linux#1]
I've put an Arch Linux ARM rootfs on my SD card, but it still gets stuck at this point.

**Comment by delroth** [comment]
Can you "fdisk -l" your SD card please?

**Comment by ghost** [comment]
Disk /dev/sdc: 119.3 GiB, 128043712512 bytes, 250085376 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x5cabae88

Device     Boot Start       End   Sectors   Size Id Type
/dev/sdc1        2048 250085375 250083328 119.3G 83 Linux

**Comment by delroth** [comment]
So... why are you pointing your kernel at p2 when you only have one partition?

**Comment by ghost** [comment]
How do I make it point to p1?

**Comment by marcan** [comment]
Kernel commandline is here: https://github.com/fail0verflow/shofel2/blob/master/usb_loader/switch.scr

**Comment by ghost** [comment]
Now its timing out waiting for hardware interrupt and giving me a SDHCI Register Dump every 5 seconds

**Comment by marcan** [comment]
That's a known issue. Try a different SD card, or maybe revert e8a92bf5 and see if that helps.

**Comment by ghost** [comment]
I reverted and got to the login screen, how am I supposed to interact with linux? Theres no keyboard

**Comment by marcan** [comment]
You pretty much need a serial port at this point. Or configure your rootfs to autostart X with a touchscreen keyboard, but that's probably going to be quite painful to do by rebooting between every attempt. WiFi also works for SSH, but only on the second and subsequent boots after a reboot for unknown reasons.

**Comment by ghost** [comment]
Is there a premade rootfs that's already setup? I cannot for the life of me figure out how to configure this rootfs. I cant chroot because differing architectures.

**Comment by shuffle2** [comment]
You should be able to use qemu to chroot and modify
