### ISSUE TITLE
Support vulkan api and sound (feature request).

### ISSUE THREAD

**Issue by iOS4all** [fail0verflow/switch-linux#4]
Hi there
As the title above can you please add support for vulkan api and sound.
Also are you running Linux on switch with HW acceleration implemented already or not yet?
Thanks.

**Comment by dankzegriefer** [comment]
Literally useless and HW acceleration is already implemented with Mesa.

**Comment by uschmann** [comment]
Why would Sound bei useless?

**Comment by delroth** [comment]
This issue is what's useless.
